#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_404.html
sudo sed i "24i '///\terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\t\troot /usr/share/nginx/html;\t\tinternal;\t} 
sudo service nginx start
